name: ci-ml-api

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          cd services/ml-api
          pip install -r requirements.txt
          pip install pytest
      - run: |
          cd services/ml-api
          PYTHONPATH=. pytest -q
